// <auto-generated />
using System;
using Kazaz.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kazaz.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117125031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_enderecos");

                    b.HasIndex("Cep")
                        .HasDatabaseName("ix_enderecos_cep");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_enderecos_cidade_id");

                    b.HasIndex("Logradouro", "Numero", "Bairro", "CidadeId")
                        .HasDatabaseName("ix_enderecos_logradouro_numero_bairro_cidade_id");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_estados");

                    b.HasIndex("Uf")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_uf");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<string>("Ibge")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ibge");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cidades");

                    b.HasIndex("Ibge")
                        .HasDatabaseName("ix_cidades_ibge");

                    b.HasIndex("EstadoId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_cidades_estado_id_nome");

                    b.ToTable("cidades", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caminho");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("caminho");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id")
                        .HasName("pk_fotos");

                    b.HasIndex("ImovelId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ix_fotos_imovel_id_ordem");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_id");

                    b.HasKey("Id")
                        .HasName("pk_imoveis");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_imoveis_codigo");

                    b.HasIndex("EnderecoId")
                        .HasDatabaseName("ix_imoveis_endereco_id");

                    b.ToTable("imoveis", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.ImovelDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAnexo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_anexo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("pk_imoveis_documentos");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_imoveis_documentos_documento_id");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("ix_imoveis_documentos_tipo_documento_id");

                    b.HasIndex("ImovelId", "TipoDocumentoId")
                        .IsUnique()
                        .HasDatabaseName("UX_imoveis_documentos_unique");

                    b.ToTable("imoveis_documentos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Origem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_origens");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_origens_nome");

                    b.ToTable("origens", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PerfilVinculoImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfis_vinculo_imovel");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_vinculo_imovel_nome");

                    b.ToTable("perfis_vinculo_imovel", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("OrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("origem_id");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .HasDatabaseName("ix_pessoas_endereco_id");

                    b.HasIndex("OrigemId")
                        .HasDatabaseName("ix_pessoas_origem_id");

                    b.ToTable("pessoas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PessoaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAnexo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_anexo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("pk_pessoas_documentos");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_pessoas_documentos_documento_id");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("ix_pessoas_documentos_tipo_documento_id");

                    b.HasIndex("PessoaId", "TipoDocumentoId")
                        .IsUnique()
                        .HasDatabaseName("UX_pessoas_documentos_unique");

                    b.ToTable("pessoas_documentos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("percentual");

                    b.Property<Guid>("PessoaFisicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_fisica_id");

                    b.HasKey("Id")
                        .HasName("pk_socios");

                    b.HasIndex("PessoaFisicaId")
                        .HasDatabaseName("ix_socios_pessoa_fisica_id");

                    b.HasIndex("EmpresaId", "PessoaFisicaId")
                        .IsUnique()
                        .HasDatabaseName("ix_socios_empresa_id_pessoa_fisica_id");

                    b.ToTable("socios", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Alvo")
                        .HasColumnType("integer")
                        .HasColumnName("alvo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id")
                        .HasName("pk_tipos_documento");

                    b.HasIndex("Alvo", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_documento_alvo_nome");

                    b.ToTable("tipos_documento", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<Guid?>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuarios_perfil_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.VinculoPessoaImovel", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<Guid>("PerfilVinculoImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_vinculo_imovel_id");

                    b.HasKey("PessoaId", "ImovelId", "PerfilVinculoImovelId")
                        .HasName("pk_vinculos_pessoa_imovel");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("ix_vinculos_pessoa_imovel_imovel_id");

                    b.HasIndex("PerfilVinculoImovelId")
                        .HasDatabaseName("ix_vinculos_pessoa_imovel_perfil_vinculo_imovel_id");

                    b.ToTable("vinculos_pessoa_imovel", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaFisica", b =>
                {
                    b.HasBaseType("Kazaz.Domain.Entities.Pessoa");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_pessoas_cpf_1");

                    b.ToTable("dados_pessoa_fisica", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.HasBaseType("Kazaz.Domain.Entities.Pessoa");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date")
                        .HasColumnName("data_abertura");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_dados_pessoa_juridica_cnpj");

                    b.ToTable("dados_pessoa_juridica", (string)null);
                });

            modelBuilder.Entity("Endereco", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enderecos_cidades_cidade_id");

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cidades_estados_estado_id");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Foto", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Imovel", "Imovel")
                        .WithMany("Fotos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fotos_imoveis_imovel_id");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Imovel", b =>
                {
                    b.HasOne("Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_enderecos_endereco_id");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.ImovelDocumento", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_documentos_documentos_documento_id");

                    b.HasOne("Kazaz.Domain.Entities.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_documentos_imoveis_imovel_id");

                    b.HasOne("Kazaz.Domain.Entities.TipoDocumento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_documentos_tipos_documento_tipo_documento_id");

                    b.Navigation("Documento");

                    b.Navigation("Imovel");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Pessoa", b =>
                {
                    b.HasOne("Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pessoas_enderecos_endereco_id");

                    b.HasOne("Kazaz.Domain.Entities.Origem", "Origem")
                        .WithMany("Clientes")
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pessoas_origens_origem_id");

                    b.Navigation("Endereco");

                    b.Navigation("Origem");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PessoaDocumento", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_documentos_documentos_documento_id");

                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_documentos_pessoas_pessoa_id");

                    b.HasOne("Kazaz.Domain.Entities.TipoDocumento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_documentos_tipos_documento_tipo_documento_id");

                    b.Navigation("Documento");

                    b.Navigation("Pessoa");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Socio", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.DadosPessoaJuridica", "Empresa")
                        .WithMany("Socios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_socios_dados_pessoas_juridicas_empresa_id");

                    b.HasOne("Kazaz.Domain.Entities.DadosPessoaFisica", "PessoaFisica")
                        .WithMany()
                        .HasForeignKey("PessoaFisicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_socios_dados_pessoas_fisicas_pessoa_fisica_id");

                    b.Navigation("Empresa");

                    b.Navigation("PessoaFisica");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .HasConstraintName("fk_usuarios_perfis_perfil_id");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.VinculoPessoaImovel", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Imovel", "Imovel")
                        .WithMany("Vinculos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_pessoa_imovel_imoveis_imovel_id");

                    b.HasOne("Kazaz.Domain.Entities.PerfilVinculoImovel", "Perfil")
                        .WithMany("Vinculos")
                        .HasForeignKey("PerfilVinculoImovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_pessoa_imovel_perfis_vinculo_imovel_perfil_vinculo");

                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Vinculos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_pessoa_imovel_pessoas_pessoa_id");

                    b.Navigation("Imovel");

                    b.Navigation("Perfil");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaFisica", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("PessoaFisica")
                        .HasForeignKey("Kazaz.Domain.Entities.DadosPessoaFisica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dados_pessoa_fisica_pessoas_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("PessoaJuridica")
                        .HasForeignKey("Kazaz.Domain.Entities.DadosPessoaJuridica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dados_pessoa_juridica_pessoas_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Imovel", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Origem", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PerfilVinculoImovel", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.Navigation("Socios");
                });
#pragma warning restore 612, 618
        }
    }
}
