// <auto-generated />
using System;
using Kazaz.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kazaz.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260103232324_CreateUsuariosPerfis")]
    partial class CreateUsuariosPerfis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_enderecos");

                    b.HasIndex("Cep")
                        .HasDatabaseName("ix_enderecos_cep");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_enderecos_cidade_id");

                    b.HasIndex("Logradouro", "Numero", "Bairro", "CidadeId")
                        .HasDatabaseName("ix_enderecos_logradouro_numero_bairro_cidade_id");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_estados");

                    b.HasIndex("Uf")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_uf");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Caracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Grupo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grupo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<string>("TipoValor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_valor");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade");

                    b.HasKey("Id")
                        .HasName("pk_caracteristicas");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_caracteristicas_nome");

                    b.ToTable("caracteristicas", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_id");

                    b.Property<string>("Ibge")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ibge");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cidades");

                    b.HasIndex("Ibge")
                        .HasDatabaseName("ix_cidades_ibge");

                    b.HasIndex("EstadoId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_cidades_estado_id_nome");

                    b.ToTable("cidades", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Conjuge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("OrgaoExpedidor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("orgao_expedidor");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_conjuges");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("ix_conjuges_pessoa_id");

                    b.ToTable("conjuges", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_contatos");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_contatos_pessoa_id");

                    b.ToTable("contatos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosComplementares", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("escolaridade");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Profissao")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("profissao");

                    b.Property<decimal?>("RendaMensal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("renda_mensal");

                    b.HasKey("Id")
                        .HasName("pk_dados_complementares");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("ix_dados_complementares_pessoa_id");

                    b.ToTable("dados_complementares", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caminho");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("caminho");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id")
                        .HasName("pk_fotos");

                    b.HasIndex("ImovelId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ix_fotos_imovel_id_ordem");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_id");

                    b.Property<int>("Finalidade")
                        .HasColumnType("integer")
                        .HasColumnName("finalidade");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TipoImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_imovel_id");

                    b.Property<string>("Titulo")
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_imoveis");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_imoveis_codigo");

                    b.HasIndex("EnderecoId")
                        .HasDatabaseName("ix_imoveis_endereco_id");

                    b.HasIndex("TipoImovelId")
                        .HasDatabaseName("ix_imoveis_tipo_imovel_id");

                    b.ToTable("imoveis", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.ImovelCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaracteristicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("caracteristica_id");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacao");

                    b.Property<bool?>("ValorBool")
                        .HasColumnType("boolean")
                        .HasColumnName("valor_bool");

                    b.Property<DateOnly?>("ValorData")
                        .HasColumnType("date")
                        .HasColumnName("valor_data");

                    b.Property<decimal?>("ValorDecimal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_decimal");

                    b.Property<int?>("ValorInt")
                        .HasColumnType("integer")
                        .HasColumnName("valor_int");

                    b.Property<string>("ValorTexto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("valor_texto");

                    b.HasKey("Id")
                        .HasName("pk_imoveis_caracteristicas");

                    b.HasIndex("CaracteristicaId")
                        .HasDatabaseName("ix_imoveis_caracteristicas_caracteristica_id");

                    b.HasIndex("ImovelId", "CaracteristicaId")
                        .IsUnique()
                        .HasDatabaseName("ux_ic_imovel_caracteristica");

                    b.ToTable("imoveis_caracteristicas", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.ImovelDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAnexo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_anexo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<Guid?>("ImovelId1")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id1");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("pk_imoveis_documentos");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_imoveis_documentos_documento_id");

                    b.HasIndex("ImovelId1")
                        .HasDatabaseName("ix_imoveis_documentos_imovel_id1");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("ix_imoveis_documentos_tipo_documento_id");

                    b.HasIndex("ImovelId", "TipoDocumentoId")
                        .IsUnique()
                        .HasDatabaseName("UX_imoveis_documentos_unique");

                    b.ToTable("imoveis_documentos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Origem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_origens");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_origens_nome");

                    b.ToTable("origens", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_nome");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PerfilVinculoImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfis_vinculo_imovel");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_vinculo_imovel_nome");

                    b.ToTable("perfis_vinculo_imovel", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("OrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("origem_id");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .HasDatabaseName("ix_pessoas_endereco_id");

                    b.HasIndex("OrigemId")
                        .HasDatabaseName("ix_pessoas_origem_id");

                    b.ToTable("pessoas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PessoaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataAnexo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_anexo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("pk_pessoas_documentos");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_pessoas_documentos_documento_id");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("ix_pessoas_documentos_tipo_documento_id");

                    b.HasIndex("PessoaId", "TipoDocumentoId")
                        .IsUnique()
                        .HasDatabaseName("UX_pessoas_documentos_unique");

                    b.ToTable("pessoas_documentos", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("percentual");

                    b.Property<Guid>("PessoaFisicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_fisica_id");

                    b.HasKey("Id")
                        .HasName("pk_socios");

                    b.HasIndex("PessoaFisicaId")
                        .HasDatabaseName("ix_socios_pessoa_fisica_id");

                    b.HasIndex("EmpresaId", "PessoaFisicaId")
                        .IsUnique()
                        .HasDatabaseName("ix_socios_empresa_id_pessoa_fisica_id");

                    b.ToTable("socios", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Alvo")
                        .HasColumnType("integer")
                        .HasColumnName("alvo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id")
                        .HasName("pk_tipos_documento");

                    b.HasIndex("Alvo", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_documento_alvo_nome");

                    b.ToTable("tipos_documento", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.TipoImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id")
                        .HasName("pk_tipo_imovel");

                    b.ToTable("tipo_imovel", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<Guid?>("PerfilId1")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id1");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuarios_perfil_id");

                    b.HasIndex("PerfilId1")
                        .HasDatabaseName("ix_usuarios_perfil_id1");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.VinculoPessoaImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<Guid>("PerfilVinculoImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_vinculo_imovel_id");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id")
                        .HasName("pk_vinculos_pessoa_imovel");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("ix_vinculos_imovel_id");

                    b.HasIndex("PerfilVinculoImovelId")
                        .HasDatabaseName("ix_vinculos_perfil_id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_vinculos_pessoa_id");

                    b.HasIndex("PessoaId", "ImovelId", "PerfilVinculoImovelId")
                        .IsUnique()
                        .HasDatabaseName("ux_vinculos_pessoa_imovel_unico");

                    b.ToTable("vinculos_pessoa_imovel", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaFisica", b =>
                {
                    b.HasBaseType("Kazaz.Domain.Entities.Pessoa");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("integer")
                        .HasColumnName("estado_civil");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nacionalidade");

                    b.Property<string>("OrgaoExpedidor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("orgao_expedidor");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_pessoas_cpf_1");

                    b.ToTable("dados_pessoa_fisica", (string)null);
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.HasBaseType("Kazaz.Domain.Entities.Pessoa");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date")
                        .HasColumnName("data_abertura");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_dados_pessoa_juridica_cnpj");

                    b.ToTable("dados_pessoa_juridica", (string)null);
                });

            modelBuilder.Entity("Endereco", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enderecos_cidades_cidade_id");

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cidades_estados_estado_id");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Conjuge", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("Conjuge")
                        .HasForeignKey("Kazaz.Domain.Entities.Conjuge", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conjuges_pessoas_pessoa_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Contato", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contatos_pessoas_pessoa_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosComplementares", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("DadosComplementares")
                        .HasForeignKey("Kazaz.Domain.Entities.DadosComplementares", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dados_complementares_pessoas_pessoa_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Foto", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Imovel", "Imovel")
                        .WithMany("Fotos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fotos_imoveis_imovel_id");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Imovel", b =>
                {
                    b.HasOne("Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_enderecos_endereco_id");

                    b.HasOne("Kazaz.Domain.Entities.TipoImovel", "TipoImovel")
                        .WithMany("Imoveis")
                        .HasForeignKey("TipoImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_tipo_imovel_tipo_imovel_id");

                    b.Navigation("Endereco");

                    b.Navigation("TipoImovel");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.ImovelCaracteristica", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Caracteristica", "Caracteristica")
                        .WithMany("ImoveisCaracteristicas")
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_caracteristicas_caracteristicas_caracteristica_id");

                    b.HasOne("Kazaz.Domain.Entities.Imovel", "Imovel")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_caracteristicas_imoveis_imovel_id");

                    b.Navigation("Caracteristica");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.ImovelDocumento", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_documentos_documentos_documento_id");

                    b.HasOne("Kazaz.Domain.Entities.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_documentos_imoveis_imovel_id");

                    b.HasOne("Kazaz.Domain.Entities.Imovel", null)
                        .WithMany("Documentos")
                        .HasForeignKey("ImovelId1")
                        .HasConstraintName("fk_imoveis_documentos_imoveis_imovel_id1");

                    b.HasOne("Kazaz.Domain.Entities.TipoDocumento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_imoveis_documentos_tipos_documento_tipo_documento_id");

                    b.Navigation("Documento");

                    b.Navigation("Imovel");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Pessoa", b =>
                {
                    b.HasOne("Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pessoas_enderecos_endereco_id");

                    b.HasOne("Kazaz.Domain.Entities.Origem", "Origem")
                        .WithMany("Clientes")
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pessoas_origens_origem_id");

                    b.Navigation("Endereco");

                    b.Navigation("Origem");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PessoaDocumento", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_documentos_documentos_documento_id");

                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_documentos_pessoas_pessoa_id");

                    b.HasOne("Kazaz.Domain.Entities.TipoDocumento", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_documentos_tipos_documento_tipo_documento_id");

                    b.Navigation("Documento");

                    b.Navigation("Pessoa");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Socio", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.DadosPessoaJuridica", "Empresa")
                        .WithMany("Socios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_socios_dados_pessoas_juridicas_empresa_id");

                    b.HasOne("Kazaz.Domain.Entities.DadosPessoaFisica", "PessoaFisica")
                        .WithMany()
                        .HasForeignKey("PessoaFisicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_socios_dados_pessoas_fisicas_pessoa_fisica_id");

                    b.Navigation("Empresa");

                    b.Navigation("PessoaFisica");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_perfis_perfil_id");

                    b.HasOne("Kazaz.Domain.Entities.Perfil", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId1")
                        .HasConstraintName("fk_usuarios_perfis_perfil_id1");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.VinculoPessoaImovel", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Imovel", "Imovel")
                        .WithMany("Vinculos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_pessoa_imovel_imoveis_imovel_id");

                    b.HasOne("Kazaz.Domain.Entities.PerfilVinculoImovel", "Perfil")
                        .WithMany("Vinculos")
                        .HasForeignKey("PerfilVinculoImovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_pessoa_imovel_perfis_vinculo_imovel_perfil_vinculo");

                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Vinculos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_pessoa_imovel_pessoas_pessoa_id");

                    b.Navigation("Imovel");

                    b.Navigation("Perfil");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaFisica", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("PessoaFisica")
                        .HasForeignKey("Kazaz.Domain.Entities.DadosPessoaFisica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dados_pessoa_fisica_pessoas_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.HasOne("Kazaz.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("PessoaJuridica")
                        .HasForeignKey("Kazaz.Domain.Entities.DadosPessoaJuridica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dados_pessoa_juridica_pessoas_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Caracteristica", b =>
                {
                    b.Navigation("ImoveisCaracteristicas");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Imovel", b =>
                {
                    b.Navigation("Caracteristicas");

                    b.Navigation("Documentos");

                    b.Navigation("Fotos");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Origem", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.PerfilVinculoImovel", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Conjuge");

                    b.Navigation("Contatos");

                    b.Navigation("DadosComplementares");

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.TipoImovel", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("Kazaz.Domain.Entities.DadosPessoaJuridica", b =>
                {
                    b.Navigation("Socios");
                });
#pragma warning restore 612, 618
        }
    }
}
